### ISSUE TITLE
sass 2.0.0 warnings when build themes

### ISSUE THREAD

**Issue by softboy99** [DevExpress/DevExtreme#18003]
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-inline-borderedwidget-inner-size - $material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $material-invalid-badge-horizontal-padding: ($material-inline-borderedwidget-inner-size - $material-invalid-badge-size) / 2 !default;
   │                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 12:45    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 3:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-inline-borderedwidget-inner-size - $material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $material-invalid-badge-horizontal-padding: ($material-inline-borderedwidget-inner-size - $material-invalid-badge-size) / 2 !default;
   │                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 12:45    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 3:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-inline-borderedwidget-inner-size - $material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $material-invalid-badge-horizontal-padding: ($material-inline-borderedwidget-inner-size - $material-invalid-badge-size) / 2 !default;
   │                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 12:45    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 3:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-invalid-badge-horizontal-padding, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
13 │ $material-invalid-badge-halfhorizontal-padding: $material-invalid-badge-horizontal-padding / 2 !default;
   │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 13:49    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 3:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-invalid-badge-horizontal-padding, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
13 │ $material-invalid-badge-halfhorizontal-padding: $material-invalid-badge-horizontal-padding / 2 !default;
   │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 13:49    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 3:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-invalid-badge-horizontal-padding, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
13 │ $material-invalid-badge-halfhorizontal-padding: $material-invalid-badge-horizontal-padding / 2 !default;
   │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 13:49    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 3:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
31 │   margin-top: -$material-invalid-badge-size / 2;
   │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 31:15   badge-settings()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 40:3    dx-invalid-material-badge()  
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 38:9   dx-fieldset-styling()        
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 137:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 7:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
31 │   margin-top: -$material-invalid-badge-size / 2;
   │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 31:15   badge-settings()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 40:3    dx-invalid-material-badge()  
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 38:9   dx-fieldset-styling()        
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 137:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 7:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
31 │   margin-top: -$material-invalid-badge-size / 2;
   │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 31:15   badge-settings()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 40:3    dx-invalid-material-badge()  
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 38:9   dx-fieldset-styling()        
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 137:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 7:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-field-min-height - $size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
52 │     margin: ($material-field-min-height - $size) / 2 0;
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 52:13  dx-field-value-widget-position()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 82:5   dx-fieldset-sizing-base()    
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 138:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 7:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-field-min-height - $size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
52 │     margin: ($material-field-min-height - $size) / 2 0;
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 52:13  dx-field-value-widget-position()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 82:5   dx-fieldset-sizing-base()    
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 138:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 7:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-field-min-height - $size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
52 │     margin: ($material-field-min-height - $size) / 2 0;
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 52:13  dx-field-value-widget-position()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 82:5   dx-fieldset-sizing-base()    
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 138:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 7:1     root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($icon-paddings, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
122 │   $icon-padding: floor($icon-paddings / 2);
    │                        ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\base\_icons.scss 122:24            dx-icon-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 21:5  dx-button-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 29:3  dx-button-onlyicon-sizing()    
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_index.scss 27:3   @use
    ..\widgets\material\tb_index 1:1                                                                                      @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 12:1  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($icon-paddings, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
122 │   $icon-padding: floor($icon-paddings / 2);
    │                        ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\base\_icons.scss 122:24            dx-icon-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 21:5  dx-button-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 29:3  dx-button-onlyicon-sizing()    
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_index.scss 27:3   @use
    ..\widgets\material\tb_index 1:1                                                                                      @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.dark.scss 12:1  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($icon-paddings, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
122 │   $icon-padding: floor($icon-paddings / 2);
    │                        ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\base\_icons.scss 122:24             dx-icon-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 21:5   dx-button-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 29:3   dx-button-onlyicon-sizing()   
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_index.scss 27:3    @use
    ..\widgets\material\tb_index 3:1                                                                                       @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 12:1  root stylesheet

WARNING: 13 repetitive deprecation warnings omitted.

WARNING: 13 repetitive deprecation warnings omitted.

WARNING: 97 repetitive deprecation warnings omitted.

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-inline-borderedwidget-inner-size - $material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $material-invalid-badge-horizontal-padding: ($material-inline-borderedwidget-inner-size - $material-invalid-badge-size) / 2 !default;
   │                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 12:45    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 3:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-invalid-badge-horizontal-padding, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
13 │ $material-invalid-badge-halfhorizontal-padding: $material-invalid-badge-horizontal-padding / 2 !default;
   │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_sizes.scss 13:49    @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 5:1     @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\typography\_index.scss 6:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 3:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$material-invalid-badge-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
31 │   margin-top: -$material-invalid-badge-size / 2;
   │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 31:15   badge-settings()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\common\_mixins.scss 40:3    dx-invalid-material-badge()  
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 38:9   dx-fieldset-styling()        
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 137:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 7:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($material-field-min-height - $size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
52 │     margin: ($material-field-min-height - $size) / 2 0;
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 52:13  dx-field-value-widget-position()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 82:5   dx-fieldset-sizing-base()    
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\fieldset\_index.scss 138:1  @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 7:1    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($icon-paddings, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
122 │   $icon-padding: floor($icon-paddings / 2);
    │                        ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\base\_icons.scss 122:24             dx-icon-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 21:5   dx-button-sizing()
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_mixins.scss 29:3   dx-button-onlyicon-sizing()   
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\widgets\material\button\_index.scss 27:3    @use
    ..\widgets\material\tb_index 3:1                                                                                       @use
    node_modules\devextreme-cli\node_modules\devextreme-themebuilder\data\scss\bundles\dx.material.orange.light.scss 12:1  root stylesheet

WARNING: 97 repetitive deprecation warnings omitted.

**Comment by babich-a** [comment]
fixed in 
https://github.com/DevExpress/DevExtreme/pull/17864
https://github.com/DevExpress/DevExtreme/pull/17860
https://github.com/DevExpress/DevExtreme/pull/17691

**Comment by softboy99** [comment]
problem still exists in v21.1.4. 

 "devextreme": "^21.1.4",
  "devextreme-vue": "^21.1.4",
"devextreme-cli": "^1.2.17",
 "devextreme-themebuilder": "^21.1.4",

**Comment by babich-a** [comment]
Hi, @softboy99 . Can you attach a full log?

**Comment by Steve-RW** [comment]
Hi @babich-a  Rolling back to 21.1.3 (in an Angular project) temporarily fixes the issue.
