### ISSUE TITLE
Memory Leak using dxTemplate

### ISSUE THREAD

**Issue by sebastianfdez** [DevExpress/DevExtreme#6564]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    Chrome
    devexteme version: 18.2.3
    devextreme-angular version: 18.2.3
- Specify the type of the issue (check one with "x"):
[X] bug Report 
[ ] feature request
[ ] support inquiry 

There is a memory leak when dxTemplate is used.

In this link there is recreation of the problem: https://stackblitz.com/edit/angular-ibh8ch 

We add a 'memoryHog' attribute to rise increase the problem.

After creating and destroying several times the component:
![image](https://user-images.githubusercontent.com/17834635/50094489-95a89b80-0213-11e9-9908-3d3825d58e83.png)

![image](https://user-images.githubusercontent.com/17834635/50094348-4d897900-0213-11e9-9fd5-f04f7b08ef7f.png)

How to reproduce using the stackblitz demo:
1) Open the DxScheduler component (click over 'Using Dx')
2) Close it (click over 'empty')
3) Take a snapshot of memory
4) Do 1) and 2) several times and click everywhere in the scheduler
5) Do 2) a last time to clean and take another snapshot

**Comment by ovchinnikov** [comment]
Thank you for the clarification. It seems that the problem is in the following code: https://github.com/DevExpress/DevExtreme/blob/a7c2d7d83d716dbb1ef6a7926f0c36d4ba9a59ee/js/ui/scheduler/ui.scheduler.work_space.js#L1665

**Comment by Yarovaya** [comment]
Hi @sebastianfdez 
I have fixed this issue in this [pull request](https://github.com/DevExpress/DevExtreme/pull/6579).

**Comment by sebastianfdez** [comment]
Thanks! Good luck

**Comment by Telem** [comment]
Unfortunately, the memory leak is still present in 18.2.4...
https://angular-1fpheh.stackblitz.io
![memleak-devextreme-2](https://user-images.githubusercontent.com/7721874/51688447-e1a9e580-1ff4-11e9-96a5-bbbf702a99b9.gif)

**Comment by San4es** [comment]
Hi @Telem

The [fix](https://github.com/DevExpress/DevExtreme/pull/6579) is included in the 18.2.5 version. Please try it.

**Comment by sebastianfdez** [comment]
Hi. How @Telem says, the problem is still appearing after the new release.
To reproduce the problem it is necessary to click over the tamplates.
Here is a gif using the updated version with https://stackblitz.com/edit/angular-ibh8ch?file=package.json

![memoryhogusingdevextreme](https://user-images.githubusercontent.com/17834635/51911587-84d27480-23d2-11e9-8c09-ceeca5f673fb.gif)

**Comment by San4es** [comment]
@sebastianfdez @Telem

Thank you for pointing out to this issue. We reproduced it. 
 
I've created a [corresponding ticket](https://www.devexpress.com/Support/Center/Question/Details/T711070/scheduler-memory-leaks-when-dxtemplate-is-used) in our Support Center. You can subscribe to it to get notification once we have any results.
